server:
  port: 8181
logging:
  level:
    com:
      sivalabs: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/catalog?useSSL=false
    username: root
    password: linuszhong
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
